# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ubuntu_x64_debug:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04
    container:
      image: 'finitereality/novelrt-build:latest'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout code'
        uses: actions/checkout@v2
        
      - name: 'Run CI Build Script'
        run: '$GITHUB_WORKSPACE/scripts/cibuild.sh --configuration DEBUG'
  ubuntu_x64_release:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04
    container:
      image: 'finitereality/novelrt-build:latest'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout code'
        uses: actions/checkout@v2
        
      - name: 'Run CI Build Script'
        run: '$GITHUB_WORKSPACE/scripts/cibuild.sh --configuration RELEASE'
  Windows_x64_Debug:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Cache vcpkg'
        id: cache-vcpkg
        uses: actions/cache@v2
        with:
            path: %GITHUB_WORKSPACE%/vcpkg
            key: ${{ runner.os }}-vcpkg-debug
        
        
      - name: 'Run Windows Setup'
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: '%GITHUB_WORKSPACE%/scripts/machine-setup.cmd'
        shell: cmd
        
      - name: 'Run CI Build Script'
        run: '%GITHUB_WORKSPACE%/scripts/cibuild.cmd'
        shell: cmd
  Windows_x64_Release:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Cache vcpkg'
        id: cache-vcpkg
        uses: actions/cache@v2
        with:
            path: %GITHUB_WORKSPACE%/vcpkg
            key: ${{ runner.os }}-vcpkg-rel
        
        
      - name: 'Run Windows Setup'
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: '%GITHUB_WORKSPACE%/scripts/machine-setup.cmd'
        shell: cmd
        
      - name: 'Run CI Build Script'
        run: '%GITHUB_WORKSPACE%/scripts/cibuild.cmd -configuration Release'
        shell: cmd




